Added manage error handling

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -10,26 +10,32 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
+      continue-on-error: false
 
     - name: List repository content
-      run: ls -la
+      run: |
+        ls -la || { echo 'Failed to list repository content'; exit 1; }
 
     - name: Setup Python 3.11
       uses: actions/setup-python@v2
       with:
         python-version: '3.11'
+      continue-on-error: false
 
     - name: Create virtual environment
-      run: python -m venv venv
+      run: |
+        python -m venv venv || { echo 'Failed to create virtual environment'; exit 1; }
 
     - name: Activate virtual environment
-      run: source ./venv/bin/activate
+      run: |
+        source ./venv/bin/activate || { echo 'Failed to activate virtual environment'; exit 1; }
 
     - name: Install dependencies
       run: |
-        pip install --upgrade pip
-        pip install -r requirements.txt
-      continue-on-error: true
+        pip install --upgrade pip || { echo 'Failed to upgrade pip'; exit 1; }
+        pip install -r requirements.txt || { echo 'Failed to install dependencies from requirements.txt'; exit 1; }
+      continue-on-error: false
 
     - name: List installed packages
-      run: pip list
+      run: |
+        pip list || { echo 'Failed to list installed packages'; exit 1; }
