deactive added

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -40,3 +40,7 @@ jobs:
     - name: List installed packages
       run: |
         pip list || { echo 'Failed to list installed packages'; exit 1; }
+    
+    - name: Deactivate virtual environment
+      run: |
+        source ./venv/bin/deactivate || { echo 'Failed to deactivate virtual environment'; exit 1; }
